### ISSUE TITLE
linear-gradient not compiling correctly

### ISSUE THREAD

**Issue by msisto** [postcss/autoprefixer-core#23]
I am observing what seems to be a bug from an older vesrion of autoprefixer-core in the current version of gulp-autoprefixer. Everything else is working a-OK.

**Source**
`background: linear-gradient(45deg, #517EA3, #326B9C);`

**Output**
`background: linear, 45deg, #517EA3, #326B9C;`

**Versions**
```
  "name": "gulp-autoprefixer",
  "version": "2.0.0",
```
```
  "name": "autoprefixer-core",
  "version": "4.0.2",
```

**Comment by ai** [comment]
You can try clean Autoprefixer in [web demo](http://simevidas.jsbin.com/gufoko/quiet) and it has no this bug. So I think you have a problem from some other Grunt plugin.

**Comment by aTei** [comment]
Have same problem. Haven't found a fix yet.
I'm using:
```
gem 'sass-rails', "~> 4.0.2"
gem 'autoprefixer-rails', '~> 5.1.5'
```

**Comment by ai** [comment]
@aTei try to remove Autoprefixer and check output again. This issue is not from Autoprefixer, but from some Sass tool.

**Comment by aTei** [comment]
I tried and you is right, something else causes problem.
