### ISSUE TITLE
`default` property `undefined` in 5.0.0

### ISSUE THREAD

**Issue by sindresorhus** [postcss/autoprefixer-core#26]
I use it to get the default browsers.

```js
console.log(require('autoprefixer-core').default);
//=> undefined
```

**Comment by ai** [comment]
Yeap, because it was moved to Browserslist.

**Comment by ai** [comment]
Use:

```js
require('browserslist').defaults
```

**Comment by ai** [comment]
I can move it back o Autoprefixer (as alias to Browserslist) if there is some user case for it.

**Comment by sindresorhus** [comment]
It's useful so I don't have to manually match `browserlist` version with the `autoprefixer-core` version to be sure I get the same result.

**Comment by sindresorhus** [comment]
It should also have been mention in the changelog as breaking change.

**Comment by ai** [comment]
Done 3c1f9b5e6c3ab68b4bbc5591954af4debce1bc33

In what case you need `autoprefixer.defaults`? Maybe it will be better just miss `browsers` option?

**Comment by sindresorhus** [comment]
> In what case you need autoprefixer.defaults?

I'm defining default options for atom-autoprefixer: https://github.com/sindresorhus/atom-autoprefixer/blob/5dfe8c0fdc0a6c64b807ffd4232aeb05c401a0c8/index.js#L44

> Maybe it will be better just miss browsers option?

Hmm, not sure what you're asking?

**Comment by ai** [comment]
If you will `browsers` option, Autoprefixer will use default value. So you doesn't need to set it manually.

**Comment by sindresorhus** [comment]
The default value is shown in the settings UI in Atom so users can edit it directly. That's why I need the value and the `browsers` option defaulting isn't very useful for that.

**Comment by ai** [comment]
OK, I add task in main repo: https://github.com/postcss/autoprefixer/issues/389

**Comment by ai** [comment]
But you should not write `browser: autoprefixer.default`. Because, if you do it, you will disable `browserslist` config.

**Comment by sindresorhus** [comment]
I'm not. I'm offering it as the default value. If the user writes something it will use that instead.
