### ISSUE TITLE
autoprefixer-core doesn't work with gulp-postcss

### ISSUE THREAD

**Issue by superlukas** [postcss/autoprefixer-core#28]
I use gulp-postcss, postcss-import and autoprefixer-core.
My CSS is one line: `@import "suitcss-base";` (from `node_modules`)
I was super happy to see postcss-import working again, but know autoprefixer-core broke apparently.

Anyway, here's the stack trace:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot call method 'indexOf' of undefined
    at /path-to/node_modules/autoprefixer-core/lib/processor.js:112:31
    at /path-to/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:190:28
    at /path-to/node_modules/postcss-import/node_modules/postcss/lib/container.js:155:24
    at Rule.each (/path-to/node_modules/postcss-import/node_modules/postcss/lib/container.js:128:20)
    at Rule.eachInside (/path-to/node_modules/postcss-import/node_modules/postcss/lib/container.js:154:21)
    at /path-to/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:158:28
    at Root.each (/path-to/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:128:20)
    at Root.eachInside (/path-to/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:154:21)
    at Root.eachDecl (/path-to/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:188:23)
    at Processor.remove (/path-to/node_modules/autoprefixer-core/lib/processor.js:99:18)
```

(Maybe it's time to let the code mature a little bit. Just saying.)

**Comment by MoOx** [comment]
Please provide a more accurate name like "vY doesn't work with postcss vX".
The title you provide don't tempt to help.

> (Maybe it's time to let the code mature a little bit. Just saying.)

What do you mean by that ?

**Comment by superlukas** [comment]
@MoOx Sorry for the vague title. Honestly, I'm not entirely sure which parts stopped working together.

> What do you mean by that ?

It's just a little frustrating. I like PostCSS a little better than Rework, but that kinda goes out the window if it breaks all the time. (Thanks for fixing postcss-import over the weekend, BTW)

**Comment by MoOx** [comment]
postcss-import has never been broken. v4.x was just compatible with postcss v3.x.
**You need to be careful a bit on what (versions) you are using, and you need to be careful on compatibility map.**
PostCSS is still young.

Upgrading all the things, all the time require some time.

PostCSS is evolving really quickly compared to rework (which is kinda unmaintained right now).
But we need some time to maintain all the plugins.
And as a end user (consumer?) you should not jump asap on new versions when there is no new killer features.

So please just be happy to consume and wait, or work with us on major upgrades.

**Comment by superlukas** [comment]
@MoOx That's what I meant. It broke my toolchain would have been a better way to put it, I guess. I upgraded to the postcss 4.x versions on Friday, which didn't work out so I downgraded to 3.x again. Then I saw you fixing postcss-import for 4.x so I upgraded again except that autoprefixer-core didn't/doesn't work anymore (I'm pretty sure it worked before — no idea what happened).

I'm talking about these versions:

```json
{
  "gulp-postcss": "4.0.2",
  "postcss-custom-properties": "3.0.0",
  "postcss-import": "5.0.0",
  "autoprefixer-core": "5.0.0"
}

**Comment by superlukas** [comment]
@MoOx Maybe we solve this the same way we did last time? A little note in the README telling the gulp/grunt/etc plugin maintainers to not jump on the new versions right away (seems to be what they're doing now).

Other gulp users who have the same problem can downgrade to this commit (w0rm/gulp-postcss@dc358c64dc52a50c6601f555837080123b862ec0) (not released to npm, unfortunately).

**Comment by MoOx** [comment]
The problem are not from the wrappers. It's cool to get them up to date when tool get upgrade.
The problem are users (us) and the ecosystem (still us). We always need some time to upgrade most of the plugins most people use.
(That's why I created a global tool to handle future-proof css (you probably see cssnext somewhere). But using something like that, you will get update only when ecosystem is ready to offer you all updates)

**Comment by ai** [comment]
Does I understand right, that problem is because PostCSS versions conflict?

So I close this issue, becuase we have this one for this problem: https://github.com/postcss/postcss/issues/163

**Comment by MoOx** [comment]
autoprefixer-core 5.0 is supposed to works with postcss 4.0, so I think there is an issue around :)
