### ISSUE TITLE
v5.1.6 issue with caniuse-db

### ISSUE THREAD

**Issue by chrisy-lili** [postcss/autoprefixer-core#33]
When building with the latest release v5.1.6, I got the error below: 
No compatible version found: caniuse-db@'>=1.0.30000077 <2.0.0'

**Comment by ai** [comment]
Very strange https://www.npmjs.com/package/caniuse-db

What is your OS? Do you run it twice?

**Comment by chrisy-lili** [comment]
I'm on Mac Yosemite. And yes, I did run it more than twice. The error message says the latest caniuse-db is ...00075, instead of ...00077.

**Comment by ai** [comment]
I think you have a issues with npm cache. You can check on npmjs.org, that latest version is 00077
