### ISSUE TITLE
I tried it it doesnt work

### ISSUE THREAD

**Issue by Soularix** [postcss/autoprefixer-core#37]
The prefixing doesnt work at all

**Comment by TrySound** [comment]
Give us some more info

**Comment by Soularix** [comment]
in cmd it said that he finished , and I find a new file in the folder dist but when I check the file I dont find any prefixes

**Comment by TrySound** [comment]
@Soularix Give us your css file

**Comment by ai** [comment]
How you add Autoprefixer to your project? You use `gulp-postcss` or what? What do you write in your project to add Autoprefixer?

**Comment by Soularix** [comment]
css file : 
body {
  font-family: Tahoma;
  font-weight: normal;
  line-height: 1.7;
  background: #F1F6F5;
  font-size:14px;
  border-radius:10px;
}
gulptask :
gulp.task('prefixing', function() {
	return gulp.src('css/style.css')
        .pipe(autoprefixer())
        .pipe(gulp.dest('dist'));
});
when I run gulp prefixing it does create a style.css file in dist but without adding border-radius prefix

**Comment by TrySound** [comment]
That's because by default autoprefixer adds prefixes to this browsers `> 1%, last 2 versions, Firefox ESR, Opera 12.1`. They all supports border-radius without prefixes. You can try add animation property for visible result.

**Comment by Soularix** [comment]
I tried transition also

**Comment by TrySound** [comment]
The same thing
http://caniuse.com/#feat=css-transitions

**Comment by Soularix** [comment]
ah last 2 versions , well ty TrySound ;)
