### ISSUE TITLE
-ms-filter always added despite caniuse data

### ISSUE THREAD

**Issue by rossPatton** [postcss/autoprefixer-core#38]
My use case:

At my work we only need to support `['last 2 versions', 'Android 4.3']`.

This works well except for one property: opacity.

According to [caniuse](http://caniuse.com/#feat=css-opacity) data on opacity support, it should not be getting prefixed according to the above rules. 

And yet, every opacity rule gets the -ms-filter prefix 
`-ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=#)`

Other rules i've tried also output the same thing, it seems that no matter what you tell autoprefixer you get the -ms-filter added.

**Comment by iamvdo** [comment]
Are you sure you're not using `postcss-opacity` ? Autoprefixer has nothing to do with `opacity`.

**Comment by ai** [comment]
Autoprefixer doesn’t handle `opacity` becausse it is a [polyfill, not prefix](https://github.com/postcss/autoprefixer#does-it-add-polyfills).

So it can’t be a Autoprefixer issue. Check other CSS tools in your environment.

**Comment by rossPatton** [comment]
Ah, you're totally right. No wonder. I was so fixated on it being autoprefixer, turns out it was nib!

Thanks
