### ISSUE TITLE
Custom Prefixes

### ISSUE THREAD

**Issue by halleycarleton** [postcss/autoprefixer-core#40]
**Feature Request**

It would be great if there was a way to add you're own prefixes in case they are not yet in the caniuse database.

For instance `:autofill` is not currently in the caniuse database, so I have to add the prefix manually(`:-webkit-autofill`).

It could something as simple as an object in the options object:

```javascript
autoprefixer({
  customPrefixes: {
    'autofill': [ '-webkit-autofill', '-otherprefix-autofill' ]
  }
});
```

**Comment by ai** [comment]
I understand that sometimes it is a simpliest way, but in long-term perspective it will be very bad.

There is very important rule in Autoprefixer’s architecture: works with browsers versions, not with a prefixes itself. There is no `-webkit-border-radius`, that should be added to all `border-radius`. It should be only `-webkit-border-radius` from Chrome X, Chrome Y with clean end-date.

Maybe there is a some cases, when custom prefixes is easy. But Can I Use author is very open. You can make a PR for a 30 minutes and maximum on next day it will be in Can I Use.

So, I don’t see any advantages of custom prefixes. Just create a PR to Can I Use.

**Comment by ai** [comment]
If you are disagree with my decision, I am open for exactly user cases, when we can’t send PR to Can I Use.

**Comment by lydell** [comment]
Lots of things are not that easy to prefix either—that's why autoprefixer has lots of ["hacks"](https://github.com/postcss/autoprefixer-core/tree/master/lib/hacks). If you need custom prefixes I think you're better making a quick little PostCSS processor for it.
