### ISSUE TITLE
Link to the Runner Guidelines somewhere in the readme

### ISSUE THREAD

**Issue by sindresorhus** [postcss/autoprefixer-core#44]
https://github.com/postcss/postcss/blob/master/Runner%20Guidelines.md

**Comment by ai** [comment]
Autoprefixer is just a PostCSS plugin, so there is no need to double all PostCSS docs in every PostCSS plugin

**Comment by sindresorhus** [comment]
I'm not asking you too. Just saying that if you want consumers of autoprefixer to follow those guidelines you need to make them more visible than just a file in a different repo.

**Comment by ai** [comment]
I understand your point, but you are looking at the Autoprefixer in wrong direction. Autoprefixer not a CSS tool anymore. Autoprefixer is just a PostCSS plugin.

So All PostCSS rules is applied to it by default. If you maintain Autoprefixer’s tool, you need to be in PostCSS community, know all news, etc.

For example, most of features in previous versions of Autoprefixer was from PostCSS. So you need to know, what will be in next PostCSS version to be ready for new Autoprefixer features.

Working with Autoprefixer without PostCSS is like a working with Compass without Sass. Or developing on Ruby on Rails without knowledge of Ruby.

**Comment by ai** [comment]
Done d333a81
