### ISSUE TITLE
Sass + Autoprefixer + Sourcemaps

### ISSUE THREAD

**Issue by MethodGrab** [postcss/autoprefixer-core#45]
If there are unicode **symbols** anywhere in the Sass (eg: pseudo element `content` property), it will cause the sourcemap to not appear in Chrome when using `gulp-sourcemaps` with `gulp-sass` + `autoprefixer`.

It seems to be just the symbols, if you replace them with hex representations then sourcemaps work.
It also appears to be autoprefixer related as compiling **with** symbols but **without** autoprefixer **does** show the sourcemap correctly.

I made a reduced test case which demonstrates the issue and has more detail here [MethodGrab/gulp-sourcemaps-test-case](https://github.com/MethodGrab/gulp-sourcemaps-test-case).

**Comment by ai** [comment]
Hm, I will look at this weekend. Thanks for good report and test case.

Can I ask you to copy this issue to PostCSS repository? Autoprefixer is just a plugin for PostCSS and map generator is there.

**Comment by MethodGrab** [comment]
Thanks! I've made an issue on postCSS as requested.
