### ISSUE TITLE
Update browserslist dependency to fix leaked global

### ISSUE THREAD

**Issue by ashleahhill** [postcss/autoprefixer-core#46]
In the 0.2.0 version of [browserslist](https://github.com/ai/browserslist/blob/0.3.1/index.js) there's a leaked global, normalizeVersion. It was fixed in 0.3.1but dependency in autoprefixer-core is [locked to ~0.2.0](https://github.com/postcss/autoprefixer-core/blob/master/package.json#L14).

**Comment by ai** [comment]
I can update it only in minor release, not in patch releases. Because Browserslist 0.3 has new features.

I will be able to write Autoprefixer 5.2 only afte I will finish PostCSS Plugin Guidelines.
