### ISSUE TITLE
Add support for image-set()

### ISSUE THREAD

**Issue by bfred-it** [postcss/autoprefixer-core#54]
All the browsers that support `image-set()` only support its prefixed version. Can this be added to autoprefixer?

Support: http://caniuse.com/#feat=css-image-set
Test page: http://cloudfour.com/examples/image-set/
Fallback: https://github.com/alex499/postcss-image-set (which at the moment doesn't seem to make much sense since there's no autoprefixer)

**Comment by ai** [comment]
Can you move this issue to main Autoprefixer repo, please? :)

**Comment by bfred-it** [comment]
Ah, sorry, I thought this one was the one with all the rules. Moved now
