### ISSUE TITLE
display: -webkit-box breaks layout in newer versions of Safari

### ISSUE THREAD

**Issue by nicolechung** [postcss/autoprefixer-core#55]
If I use a site like:

```
http://the-echoplex.net/flexyboxes/
```

When I add

```
display: flex
```

It adds the following prefixes:

```
display: -ms-flexbox;
display: -webkit-flex;
display: flex;
```

It does not include ```display: -webkit-box``` which breaks my container layout.

Instead of my boxes fitting inside my container, when -webkit-box is added, the boxes attempt to stretch out my container...only in Safari (using 8.0.5).

Is there a way to change this with Autoprefixer?

**Comment by ai** [comment]
How Flexyboxes is affected to Autoprefixer?

**Comment by nicolechung** [comment]
What I mean is this:

```
display: -webkit-box
```

Is for old Safari (/* OLD - iOS 6-, Safari 3.1-6 */) but it appears that newer versions of Safari, if they see ```-webkit-box```, it breaks the flex layout. Omitting this allows the layout to work properly in newer browsers.

Is it possible to have a setting to disable auto-prefixer from adding:

```
display: -webkit-box
```

If I add:

```
display: flex
```

**Comment by ai** [comment]
Just don't use Flexuboxes and use only Autoprefixer, it will do all correctly

**Comment by nicolechung** [comment]
NVM, my bad (sorry). Looks like Safari just started to ignore ```-webkit-box``` again.
