### ISSUE TITLE
Not possible to use -webkit-line-clamp 

### ISSUE THREAD

**Issue by nabaroa** [postcss/autoprefixer-core#60]
Is imposible to use -webkit-line-clamp property because the autoprefixer removes 'display: -webkit-box'.

.foo {
    display: -webkit-box;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
}

**Comment by ai** [comment]
First, why you use only `-webkit-` prefixes in your CSS? It is a very bad practice. You should write unprefixed versions like `display: flex`.

**Comment by ai** [comment]
Second, I tried to input

```
.foo {
display: -webkit-box;
-webkit-line-clamp: 3;
-webkit-box-orient: vertical;
}
```

to [interactive demo](http://simevidas.jsbin.com/gufoko/quiet) and I got

```.foo {
display: -webkit-box;
-webkit-line-clamp: 3;
-webkit-box-orient: vertical;
}
```

So seems like Autoprefixer do not remove anything.

**Comment by nabaroa** [comment]
Yes, I know that is a bad practice but I'm using fallbacks to other browsers.
I want to use this weird webKit flexbox way: http://dropshado.ws/post/1015351370/webkit-line-clamp 
I'm using gulp-autoprefixer in the gulpfile and the output I get is: 
.foo{
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;
}
The autoprefixer is removing 'display: -webkit-box;'.
I understand that is a stilted and non standard solution and you are creating useful standard tools. 

Thanks for your prompt response

**Comment by TrySound** [comment]
@nabaroa Show your build code.

**Comment by ai** [comment]
What version of Autoprefixer you use and what is your `browser` options for it?

**Comment by nabaroa** [comment]
Sure! I'm using too restrictive browser options. I've changed them and is working perfectly. Thank you for your help. <3
