### ISSUE TITLE
gulp autoprefixer returns invalid icon content of font-awesome

### ISSUE THREAD

**Issue by godesign** [postcss/autoprefixer-core#62]
I've just setup the following Gulp task for SASS, using gulp-autoprefixer which causing a problem handling font-awesome icon "content".

**The way it works (without gulp-autoprefixer)**

    gulp.task('sass', function() {
    
      gulp.src(['./src/vendor/style.scss',
            './src/app/style.scss'])
          .pipe(sourcemaps.init())
          .pipe(sass({outputStyle: 'compressed'}).on('error', sass.logError))
          .pipe(concat('style.css'))
          .pipe(sourcemaps.write('./'))
          .pipe(gulp.dest('./public/css'));
    
    });

**That works fine** and it outputs the result I expect.

An example of the user-icon (**without gulp-autoprefixer**):

    .fa-user:before {
        content: "";
    }

---

**The way it breaks (with gulp-autoprefixer)**

If I now add autoprefixer to this task - like:

    gulp.task('sass', function() {
    
      gulp.src(['./src/vendor/style.scss',
            './src/app/style.scss'])
          .pipe(sourcemaps.init())
          .pipe(sass({outputStyle: 'compressed'}).on('error', sass.logError))
          .pipe(concat('style.css'))
          .pipe(prefix({
            browsers: ['> 1%', 'last 2 versions', 'Firefox ESR', 'Opera 12.1'],
            cascade: false
          }))
          .pipe(sourcemaps.write('./'))
          .pipe(gulp.dest('./public/css'));
    
    });

The **output breaks** now. This is what I get for fa-user **(with gulp-autoprefixer)**:

    .fa-user:before {
        content: "ï€‡";
    }

It seems like there is a problem with the charset (UTF-8 / UTF-16).

Is there any possibility to avoid that behaviour with gulp-autoprefixer?

**Comment by ai** [comment]
I use Autoprefixer Rails with FontAwesome on my project. Everything is fine. So it is not part of core package.

First, try out [gulp-postcss](https://github.com/postcss/gulp-postcss), it is a official way to use any PostCSS plugin. Because of more plugins we have more cases to tests.

If it will not help, open a issue in `gulp-postcss`.
