### ISSUE TITLE
Deprecation warnings with PostCSS 5.0

### ISSUE THREAD

**Issue by silverwind** [postcss/autoprefixer-core#66]
Looks the module still works, but as it's installed alongside PostCSS there's nothing stopping the 5.0.0 bump, which results in these warnings for me:

````
Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Node#style() is deprecated. Use Node#raw()
Node#before is deprecated. Use Node#raws.before
Node#_value was deprecated. Use Node#raws.value
````

**Comment by silverwind** [comment]
Just saw that `postcss` is actually a dependency of `autoprefixer-core`. Would you advice not installing PostCSS directly in my module like this?

````js
 "autoprefixer-core": "^5.2.1",
 "postcss": "^5.0.0",
````

**Comment by silverwind** [comment]
Looks like a reinstall of all modules actually resolved this.

````
├─┬ autoprefixer-core@5.2.1
│ └── postcss@4.1.16
└── postcss@5.0.0
````

**Comment by ai** [comment]
Autoprefixer will moved to PostCSS 5.0 in 6.0 release

**Comment by joseluisq** [comment]
@ai What can you suggest instead?

**Comment by ai** [comment]
@joseluisq I do not see a big problems with warnings. Just ignore it.

Also you can downgrade PostCSS runner (like `gulp-postcss`) to PostCSS 4.x. But it is not ideal way.

Sorry, I just have no time in this month to release 6.0 — because of major update we need o implement many awesome things :).

**Comment by joseluisq** [comment]
@ai Thanks I understand 
`PostCSS` is cool ! in fact `autoprefixer-core v5.x` and `PostCSS v4.x` work fine.
Sounds great ! So I await for your next release ! :+1:
