### ISSUE TITLE
CSS property "word-wrap" has been renamed to "overflow-wrap"

### ISSUE THREAD

**Issue by steffenweber** [postcss/autoprefixer-core#68]
I've read at http://jonibologna.com/word-wrapping-woes/ that the CSS property `word-wrap` has been renamed to `overflow-wrap` in the spec (http://www.w3.org/TR/css3-text/#overflow-wrap). The new name has relatively poor browser support: http://caniuse.com/#search=overflow-wrap

I I know that this issue is not technically about prefixing but very similar in spirit. Could Autoprefixer complement `overflow-wrap` properties with the equivalent `word-wrap` property?

Note that the spec says:

> For legacy reasons, UAs must treat ‘word-wrap’ as an alternate name for the ‘overflow-wrap’ property, as if it were a shorthand of ‘overflow-wrap’.

So in theory it would be fine to just use `word-wrap` forever and just ignore its new name. But that does not seem right to me. ;-)

**Comment by ai** [comment]
Autoprefixer is only about prefixes. Not poyfills. This is why it do not convert `::before` to `:before` or `will-change` to 3D hack.

Write other PostCSS plugin for this task. It will be very easy. See [postcss-will-change](https://github.com/postcss/postcss-will-change).
